spring:
  profiles:
    active: dev # dev prod
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.file-path-prefix}
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      filters: stat,wall,log4j
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
server:
  port: 8080
  session-timeout: 30
  tomcat:
      uri-encoding: UTF-8
mybatis:
    mapper-locations: classpath:/mybatis/**/*Mapper.xml
velocity:
    attributes:
      _application_static_url:
      require_static_url: /static
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.137.130:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
file:
  file-path-prefix: E:/xheq/file/
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/xhitd02_business?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
file:
  file-path-prefix: D:/xheq/file/